spring:
  application:
    name: mcp-liveperson-server
  ai:
    mcp:
      server:
        name: liveperson-mcp-server
        version: 0.2.0
        type: SYNC
        sse-endpoint: /mcp/sse
        capabilities:
          tool: true
          resource: false
          prompt: true
          completion: false

lp:
  account-id: "${LP_ACCOUNT_ID}"
  domains:
    sentinel: "${LP_SENTINEL_DOMAIN}"
    idp: "${LP_IDP_DOMAIN}"
    messaging: "${LP_MSG_DOMAIN}"
  auth:
    client-id: "${LP_CLIENT_ID}"
    client-secret: "${LP_CLIENT_SECRET}"
    renew-skew-seconds: ${LP_JWT_RENEW_SKEW:300}
  client:
    client-source: "${LP_CLIENT_SOURCE:mcp-liveperson-server}"

server:
  port: 8080

logging:
  level:
    root: INFO
    com.gtrefs.liveperson.mcp.poc: INFO
